export default {
  baseSize: 16,
  grid: 12,
  gutterWidth: 1,
  container: {
    sm: 46,
    md: 61,
    lg: 76,
  },
  breakpoints: {
    xs: 0,
    sm: 576,
    md: 768,
    lg: 992,
  },
  border: {
    radius: '0.4rem',
  },
  fonts: {
    family: {
      primary: 'Nunito, sans-serif',
      secondary: 'Source Sans Pro, sans-serif',
    },
    weights: {
      light: 300,
      regular: 400,
      bold: 700,
    },
    tagProperties: {
      h1: { size: '2rem', weight: 500, family: 'Nunito, sans-serif' },
      h2: { size: '1.8rem', weight: 500, family: 'Nunito, sans-serif' },
      h3: { size: '1.5rem', weight: 500, family: 'Nunito, sans-serif' },
      h4: { size: '1.3rem', weight: 500, family: 'Nunito, sans-serif' },
      h5: { size: '1rem', weight: 500, family: 'Nunito, sans-serif' },
      h6: { size: '0.8rem', weight: 500, family: 'Nunito, sans-serif' },
      subheading1: { size: '1.2rem', weight: 400, family: 'Nunito, sans-serif' },
      subheading2: { size: '1rem', weight: 400, family: 'Nunito, sans-serif' },
      body1: { size: '1rem', weight: 300, family: 'Source Sans Pro, sans-serif' },
      body2: { size: '0.8rem', weight: 300, family: 'Source Sans Pro, sans-serif' },
    },
  },
  colors: {
    primary: '#6D28D9',
    secondary: '#F5F3FF',
    black: '#000',
    white: '#fff',
    neutral100: '#F3F4F6',
    neutral200: '#EFF0F5',
    neutral300: '#D1D5DB',
    neutral400: '#6B7280',
    neutral500: '#333945',
    error: '#EF4444',
    success: '#10B981',
    warning: '#FBBF24',
  },
} as const;
